:P just playing

diff --git a/tools/testing/selftests/net/Makefile b/tools/testing/selftests/net/Makefile
--- a/tools/testing/selftests/net/Makefile
+++ b/tools/testing/selftests/net/Makefile
@@ -14,6 +14,16 @@ all: $(NET_PROGS)
 run_tests: all
 	@/bin/sh ./run_netsocktests || echo "sockettests: [FAIL]"
 	@/bin/sh ./run_afpackettests || echo "afpackettests: [FAIL]"
+<<<<<<< HEAD
 
+=======
+	@if /sbin/modprobe test_bpf ; then \
+		/sbin/rmmod test_bpf; \
+		echo "test_bpf: ok"; \
+	else \
+		echo "test_bpf: [FAIL]"; \
+		exit 1; \
+	fi
+>>>>>>> v3.18
 clean:
 	$(RM) $(NET_PROGS)
diff --git a/tools/testing/selftests/vm/run_vmtests b/tools/testing/selftests/vm/run_vmtests
--- a/tools/testing/selftests/vm/run_vmtests
+++ b/tools/testing/selftests/vm/run_vmtests
@@ -4,6 +4,10 @@
 #we need 256M, below is the size in kB
 needmem=262144
 mnt=./huge
+<<<<<<< HEAD
+=======
+exitcode=0
+>>>>>>> v3.18
 
 #get pagesize and freepages from /proc/meminfo
 while read name size unit; do
@@ -41,6 +45,10 @@ echo "--------------------"
 ./hugepage-mmap
 if [ $? -ne 0 ]; then
 	echo "[FAIL]"
+<<<<<<< HEAD
+=======
+	exitcode=1
+>>>>>>> v3.18
 else
 	echo "[PASS]"
 fi
@@ -55,6 +63,10 @@ echo "--------------------"
 ./hugepage-shm
 if [ $? -ne 0 ]; then
 	echo "[FAIL]"
+<<<<<<< HEAD
+=======
+	exitcode=1
+>>>>>>> v3.18
 else
 	echo "[PASS]"
 fi
@@ -67,6 +79,21 @@ echo "--------------------"
 ./map_hugetlb
 if [ $? -ne 0 ]; then
 	echo "[FAIL]"
+<<<<<<< HEAD
+=======
+	exitcode=1
+else
+	echo "[PASS]"
+fi
+
+echo "--------------------"
+echo "running hugetlbfstest"
+echo "--------------------"
+./hugetlbfstest
+if [ $? -ne 0 ]; then
+	echo "[FAIL]"
+	exitcode=1
+>>>>>>> v3.18
 else
 	echo "[PASS]"
 fi
@@ -75,3 +102,7 @@ fi
 umount $mnt
 rm -rf $mnt
 echo $nr_hugepgs > /proc/sys/vm/nr_hugepages
+<<<<<<< HEAD
+=======
+exit $exitcode
+>>>>>>> v3.18
